### PR TITLE
Drop the native module in favor of `RCTStatusBarManager`

### PR DESCRIPTION
**Pull request by jgkim**
The recent commit 614e8ca doesn't work as expected, and it seems like we don't need to use the native module anymore. `RCTStatusBarManager` of `React Native` has the same functionality.

### CODE REVIEW

**Comment by 0xashu** [comment]
@brentvatne 
The PR should be merged, it does solve some problems of the project.

**Comment by brentvatne** [comment]
Would either of you like to maintain the project? I do not use this anymore. brentvatne@gmail.com

**Comment by jgkim** [comment]
@brentvatne Though there is a few lines of code left, I can maintain the project since I'm still using this. My npm username is the same as the GitHub one.

**Comment by brentvatne** [comment]
@jgkim - I made you a collaborator and added you as owner on npm. I tried to transfer the repo to you but you need to delete your fork first:

screen shot 2016-11-25 at 12 08 19 pm

Thanks for taking it over :) :)

**Comment by jgkim** [comment]
@brentvatne - Thanks. I've deleted my fork so now you can transfer the repo if you want. :)

**Pull request merged**
